### ISSUE TITLE
Don't catch etree.ParseError on Python <=2.6

### ISSUE THREAD

**Issue by sampsyo** [beetbox/pylastfp#3]
This reflects a bug filed on the beets bug tracker:
http://code.google.com/p/beets/issues/detail?id=246

etree.ParseError does not exist in Python 2.6 (it was added in 2.7). In order to preserve compatibility, we should detect when this exception is not available.

A fix like this one should suffice:

https://github.com/alastair/python-musicbrainz-ngs/commit/e00802b7533fb7f170cd7c2d260e4ae16a0f4523

**Comment by cclauss** [comment]
I think we can __close__ this issue.  Python 2.6 went EOL 4+ years ago.
* https://docs.python.org/devguide/index.html#branchstatus
